import { ICitation } from '../../models/message.model';

export class ConfidenceCalculator {
  /**
   * Computes the confidence scores for an AI response based on retrieved citations
   * and the generated text.
   * 
   * @param aiResponse The text generated by the LLM
   * @param citations The citations retrieved by RAG
   */
  public calculateConfidence(aiResponse: string, citations: ICitation[]): {
    source: number;
    hallucination: number;
    overall: number;
  } {
    if (!citations || citations.length === 0) {
      return { source: 0, hallucination: 0, overall: 0 };
    }

    const sourceConfidence = this.calculateSourceConfidence(citations);
    const hallucinationConfidence = this.calculateHallucinationConfidence(aiResponse, citations);
    
    // Weighting: 40% source retrieval quality, 60% grounding/overlap quality
    const overall = (sourceConfidence * 0.4) + (hallucinationConfidence * 0.6);

    return {
      source: Math.round(sourceConfidence * 100) / 100,
      hallucination: Math.round(hallucinationConfidence * 100) / 100,
      overall: Math.round(overall * 100) / 100
    };
  }

  /**
   * Averages the similarity scores of the citations.
   */
  private calculateSourceConfidence(citations: ICitation[]): number {
    const totalSimilarity = citations.reduce((sum, cit) => sum + cit.similarityScore, 0);
    const avg = totalSimilarity / citations.length;
    // Normalize if scores can exceed 1 (e.g., dot product). We assume cosine similarity 0-1 for this system.
    return Math.min(Math.max(avg, 0), 1);
  }

  /**
   * Heuristic: calculates word overlap between the AI's response and the provided context.
   * A higher overlap implies higher grounding (lower hallucination).
   * Note: This is a simplistic heuristic. Advanced systems might use a small evaluator LLM.
   */
  private calculateHallucinationConfidence(aiResponse: string, citations: ICitation[]): number {
    const combinedContext = citations.map(c => c.text).join(' ').toLowerCase();
    const responseWords = aiResponse
      .toLowerCase()
      .replace(/[^\w\s]/gi, '')
      .split(/\s+/)
      .filter(w => w.length > 3); // Ignore stop-words implicitly by length > 3 for simplicity

    if (responseWords.length === 0) return 1;

    let matchCount = 0;
    const contextWordsSet = new Set(
      combinedContext.replace(/[^\w\s]/gi, '').split(/\s+/)
    );

    for (const word of responseWords) {
      if (contextWordsSet.has(word)) {
        matchCount++;
      }
    }

    const overlapRatio = matchCount / responseWords.length;
    
    // An overlap ratio of ~30-40% is usually very good for natural language generation
    // since the LLM adds grammar, transitions, and reasoning. We scale it up.
    // Cap at 1.0.
    const normalizedScore = Math.min(overlapRatio * 2.5, 1.0);
    return normalizedScore;
  }
}
